name = "OptimalBath"
uuid = "ff45c333-ce72-433e-9e30-5feb6da7c95a"
authors = ["martinsw01 <martin.s.winther@gmail.com>"]
version = "1.0.0-DEV"

[deps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SinFVM = "5fce8053-0ea8-4994-9de9-3497d067a1ac"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.10"

[sources]
SinFVM = {url = "https://github.com/sintefmath/SinFVM.jl", rev="main"}